#!/bin/bash

RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')
YELLOW=$(echo -en '\033[00;33m')
BLUE=$(echo -en '\033[00;34m')
MAGENTA=$(echo -en '\033[00;35m')
PURPLE=$(echo -en '\033[00;35m')
CYAN=$(echo -en '\033[00;36m')
LIGHTGRAY=$(echo -en '\033[00;37m')
LRED=$(echo -en '\033[01;31m')
LGREEN=$(echo -en '\033[01;32m')
LYELLOW=$(echo -en '\033[01;33m')
LBLUE=$(echo -en '\033[01;34m')
LMAGENTA=$(echo -en '\033[01;35m')
LPURPLE=$(echo -en '\033[01;35m')
LCYAN=$(echo -en '\033[01;36m')
WHITE=$(echo -en '\033[01;37m')
ORANGE=$(echo -en '\033[01;33m')
DARK=$(echo -en '\033[01;30m')

OS=`grep ^NAME /etc/os-release | sed 's/\"//g' | sed 's/.*=//g'`
KERNEL=`uname -r`
RAM=$(echo "$((`awk '/MemTotal/{print $2}' /proc/meminfo`/1024))")
RAM_USED=$(echo $((`awk '/MemAvailable/{print $2}' /proc/meminfo`/1024)))
RAM_USED=$(echo $((RAM-RAM_USED)))
UPTIME=`echo $(uptime | awk '{print $3}' | sed 's/,//g' | sed 's/\:/h /g')m`
HOSTNAME=`hostnamectl | awk 'NR==1{print $3}'`
USERNAME=`whoami`

echo -e "${BLUE}┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo -e "${BLUE}┃${RESTORE}   .${ORANGE}~${RESTORE}.   ${BLUE}┃  ${BLUE}$HOSTNAME${RESTORE}@${BLUE}$USERNAME""\t\t\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}   ${DARK}/${ORANGE}V${RESTORE}${DARK}\   ${BLUE}┃  ${PURPLE}os${RESTORE}\t\t$OS""\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}  ${DARK}/${WHITE}/ \\\\${DARK}\  ${BLUE}┃  ${PURPLE}uptime${RESTORE}\t$UPTIME""\t\t\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE} ${DARK}/${WHITE}(   )${DARK}\ ${BLUE}┃  ${PURPLE}kernel${RESTORE}\t$KERNEL""\t\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}  ${DARK}^${WHITE}\`${ORANGE}~${WHITE}'${DARK}^  ${BLUE}┃  ${PURPLE}ram${RESTORE}\t""$RAM_USED"M / "$RAM"M"\t\t"${BLUE}┃
echo -e "${BLUE}┗━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
